# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5708858e79b6e6262d928c639d0134b603647113b118003a379126fb711bb8e2bece840469a7b4a972fe5b2bea07f6491febdf51a3a6e99d04d48c5f23fdc065

test:
  secret_key_base: 8d1b6103609eb4a26ea2167c20146678bfc8386333b4eca5b8d465a588e665da8ef0a97f2e6db81f8891b1f71803e9615f856f611498ec91b1e874f68e6ce273

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
